### ISSUE TITLE
its not running

### ISSUE THREAD

**Issue by sravanzeal** [dworkinnn/navigation_drawer#1]
hi team, 
the project files shows missing prefabs and giving errors.
can you please solve this issue.
![screenshot 2018-10-12 at 10 53 46 am](https://user-images.githubusercontent.com/17290569/46849445-25455e80-ce0d-11e8-8f87-5c7c490bb823.png)

**Comment by psvantares** [comment]
hi
you need to open the project Unity 2018.2.1f1 and higher.
in unity 2017.x.x and below, prefabs need to be rebuilt on their own.
